### ISSUE TITLE
Rename load-bash-alias-load-bash-alias-into-eshell to load-bash-alias-into-eshell

### ISSUE THREAD

**Issue by Fuco1** [daviderestivo/load-bash-alias#2]
I think the prefix being duplicated makes little sense.  We still have the package prefix and the new name is shorter and reads much easier.

To keep BC you can alias the old one to the new one and mark it obsolete.

**Comment by daviderestivo** [comment]
Hi Matus,

to be honest I tend to agree with you 👍 . The function name is a little bit prolix. I will rename it.

Thanks for the suggestion,
Davide

**Comment by Fuco1** [comment]
Thanks! Superb idea for a package by the way!

**Comment by daviderestivo** [comment]
Hi Fuco,

[I've done it](
https://github.com/daviderestivo/load-bash-alias/commit/d2dca7e7e546582a5f8aa339b276fe8a89f57771). I hope I did it the right way. Since I'm not a veteran of elisp any suggestion is more than welcome :). Please lemme know so I can close the issue.

Regards,
Davide

**Comment by daviderestivo** [comment]
Hi Matus,

[I have replaced](https://github.com/daviderestivo/load-bash-alias/commit/ecfd3b9ff748e35de36c0cd1ef50df5d7694a276) **defalias+make-obsolete** with **define-obsolete-function-alias**.

Regards,
Davide
